// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyuPoQOISgCKXo3eMfvtG4DfHvExWMKj0',
    appId: '1:504885625160:web:980ace202462cafadd337d',
    messagingSenderId: '504885625160',
    projectId: 'myportfolio-49a35',
    authDomain: 'myportfolio-49a35.firebaseapp.com',
    storageBucket: 'myportfolio-49a35.appspot.com',
    measurementId: 'G-ETJ6P6JD7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANs4k72ViJuOXaVOCejk0zTTi0iy3ENVM',
    appId: '1:504885625160:android:78f50504c22970ebdd337d',
    messagingSenderId: '504885625160',
    projectId: 'myportfolio-49a35',
    storageBucket: 'myportfolio-49a35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPIh6GzvcQFtq9FKeqaY4TR1IPHVS5Rn4',
    appId: '1:504885625160:ios:cb8f5c0f004ed368dd337d',
    messagingSenderId: '504885625160',
    projectId: 'myportfolio-49a35',
    storageBucket: 'myportfolio-49a35.appspot.com',
    iosBundleId: 'com.example.senaecelik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPIh6GzvcQFtq9FKeqaY4TR1IPHVS5Rn4',
    appId: '1:504885625160:ios:76a96924ae842279dd337d',
    messagingSenderId: '504885625160',
    projectId: 'myportfolio-49a35',
    storageBucket: 'myportfolio-49a35.appspot.com',
    iosBundleId: 'com.example.senaecelik.RunnerTests',
  );
}
