// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:senaecelik/data/model/reflector.dart' as prefix0;
import 'package:senaecelik/data/model/user_model.dart' as prefix1;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'UserModel',
            r'.UserModel',
            134217735,
            0,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => (
                      {name,
                      surname,
                      image,
                      adress,
                      email,
                      resumeLink,
                      jobList,
                      socialLink,
                      about,
                      project}) =>
                  b
                      ? prefix1.UserModel(
                          about: about,
                          adress: adress,
                          email: email,
                          image: image,
                          jobList: jobList,
                          name: name,
                          project: project,
                          resumeLink: resumeLink,
                          socialLink: socialLink,
                          surname: surname)
                      : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix1.UserModel.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'name': 0,
              r'name=': 1,
              r'surname': 0,
              r'surname=': 1,
              r'image': 0,
              r'image=': 1,
              r'adress': 0,
              r'adress=': 1,
              r'resumeLink': 0,
              r'resumeLink=': 1,
              r'email': 0,
              r'email=': 1,
              r'jobList': 0,
              r'jobList=': 1,
              r'socialLink': 0,
              r'socialLink=': 1,
              r'about': 0,
              r'about=': 1,
              r'project': 0,
              r'project=': 1
            })
      ],
      null,
      null,
      <Type>[prefix1.UserModel],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toJson': (dynamic instance) => instance.toJson,
        r'name': (dynamic instance) => instance.name,
        r'surname': (dynamic instance) => instance.surname,
        r'image': (dynamic instance) => instance.image,
        r'adress': (dynamic instance) => instance.adress,
        r'resumeLink': (dynamic instance) => instance.resumeLink,
        r'email': (dynamic instance) => instance.email,
        r'jobList': (dynamic instance) => instance.jobList,
        r'socialLink': (dynamic instance) => instance.socialLink,
        r'about': (dynamic instance) => instance.about,
        r'project': (dynamic instance) => instance.project
      },
      {
        r'name=': (dynamic instance, value) => instance.name = value,
        r'surname=': (dynamic instance, value) => instance.surname = value,
        r'image=': (dynamic instance, value) => instance.image = value,
        r'adress=': (dynamic instance, value) => instance.adress = value,
        r'resumeLink=': (dynamic instance, value) =>
            instance.resumeLink = value,
        r'email=': (dynamic instance, value) => instance.email = value,
        r'jobList=': (dynamic instance, value) => instance.jobList = value,
        r'socialLink=': (dynamic instance, value) =>
            instance.socialLink = value,
        r'about=': (dynamic instance, value) => instance.about = value,
        r'project=': (dynamic instance, value) => instance.project = value
      },
      null,
      [
        const [0, 0, null],
        const [1, 0, null],
        const [
          0,
          0,
          const [
            #name,
            #surname,
            #image,
            #adress,
            #email,
            #resumeLink,
            #jobList,
            #socialLink,
            #about,
            #project
          ]
        ]
      ])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
